---
title: "strings_and_factors"
output: html_document
date: "2025-10-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries 

```{r}
library(rvest)
library(p8105.datasets)
library(stringr)
library(forcats)
library(tidyverse)
library(rvest)
library(httr)
```

## Mostly use string vectors 

```{r}
string_vec= c("my","name","is","jeff")
str_detect(string_vec,"jeff")
str_detect(string_vec,"e")
str_detect(string_vec,"Jeff") #note this is case sensitive 

str_replace(string_vec, "jeff","Jeff")
str_replace(string_vec,"e","")
str_remove(string_vec,"e")
```

(copied from p8105) 

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "i think")
str_detect(string_vec, "^i think") #look at the beginning 
str_detect(string_vec, "i think$") #look at the end 

str_remove(string_vec,"i think$")
```

Pumpkin themed example ! 

```{r}
string_vec = c(
  "Time for a Pumpkin Spice Latte!",
  "went to the #pumpkinpatch last weekend",
  "Pumpkin Pie is obviously the best pie",
  "SMASHING PUMPKINS -- LIVE IN CONCERT!!"
  )

str_detect(string_vec,"pumpkin")
str_detect(string_vec,"Pumpkin")
str_detect(string_vec,"[Pp]umpkin") #bracket says that anything in there counts but anything outside of it must match 
```

Let's get a bit more complicated 

```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )

str_detect(string_vec, "^[0-9][a-zA-Z]")
```

```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )

str_detect(string_vec, "7.1") #the dot recognized as -,"",. 
str_detect(string_vec, "7\\.1") #\\ makes it so that only looks for 7.1 

```

## Factors 

```{r}
vec_sex = factor(c("male", "male", "female", "female"))
vec_sex ##Output shows us that there are levels 

as.numeric(vec_sex)
vec_sex=fct_inorder(vec_sex)
vec_sex #changes the order 
```

# Revisiting NSDUH 

## Extracting tables: Import NSDUH DATA from the web 

```{r}
URL = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html=read_html(URL)
```

This is an easy case becasue instead of using a CSS selector we are able to jsut get the tables directly 

```{r}
ndsuh_df= drug_use_html %>% #definitely still needs to tidied: things were made strings instead of numbers; and columns are containing more than one thing age and date 
  html_table() %>% 
  first() %>% 
  slice(-1)
```

No we must do the tidying... 

```{r}
marj_df =
  ndsuh_df %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(
    -State,
    names_to="age_year",
    values_to="percent"
  ) %>% 
  separate(age_year,into=c("age","year"), sep="\\(") %>% 
  mutate(
    year=str_remove(year,"\\)"),
    percent=str_remove(percent,"[a-c]$"),
    percent=as.numeric(percent)
  ) %>% 
  filter(
    !(State %in% c("Total U.S.","Northeast","Midwest","South","West"))
  )
```

Let's make a quick plot 

```{r}
marj_df %>% 
  filter(age=="12-17") %>% 
  mutate(State=fct_reorder(State,percent)) %>% 
  ggplot(aes(x=State,y=percent,color=year))+
  geom_point() +
  theme(axis.text.x=element_text(angle=90,hjust=1))
```



